### ISSUE TITLE
ODE solvers

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#1309]
- [x] prepare c++ code of ODE system to test
- [x] standardize ODE system file
- [x] link solve solution to the platform
