### ISSUE TITLE
#3195: Plate Viewer

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#3195]
This is to support working with experimental plates (96 wells, 384 wells, 1536 wells).

Basic features:

- [ ] use dataframe in a vertical format (row, col, value1, value2, etc) as a data source
- [ ] render as a grid
- [ ] render in a grid cell

Advanced features:
- [ ] editing content
- [ ] supporting layouts
- [ ] layout: dilution series

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-17247

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

https://dev.datagrok.ai/p/askalkin.medchem_4/Med_Chem

**Comment by dnillovna** [comment]
> Olesia Pavlenko commented in Jira:

Tested as a part of Med Chem dashboard.
