### ISSUE TITLE
HELM package

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#700]
[HELM Datagrok package](https://github.com/datagrok-ai/public/tree/master/packages/Helm) provides support for [HELM notation](https://pistoiaalliance.atlassian.net/wiki/spaces/HELM/overview) (Hierarchical Editing Language for Macromolecules) - a single notation that can encode the structure of complex biomolecules including diverse polymers, non-natural monomers and complex attachment points.

### Basic features
- [x]  Automatic detection of HELM values in datasets
- [x]  Rendering
- [x]  Editing
- [x]  Conversion to SMARTS and MOLBLOCK

### Advanced features
- [x] Integration with the [HELM2WebService](https://github.com/PistoiaHELM/HELM2WebService) (convert to fasta, convert to RNA, convert to peptide)
- [x] Support for company-specific monomer libraries
- [x] Management tool for monomer libraries (integrated with the security and privileges)
- [x] Similarity and diversity analyses
- [x] HELM space (UMAP or t-SNE based on the distance)
- [x] Activity cliffs analysis (based on the HELM space)

### Known issues
- [x] Browser crashes when scrolling (looks like an issue with instantiating too many HELM viewers)
