### ISSUE TITLE
Bio: to atomic level  enhancements round 1

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#933]
- [x] move the code to bio library
- [x] generate datasets with all monomer pairs (for peptides and chem modifications and for rna)
- [x] refactor the code employing more efficient data structures
- [x] improve positioning of monomers upon chaining
- [x] add functionality for nucleotides
