### ISSUE TITLE
Electron-based desktop version of Datagrok

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#941]
- [ ] make a special build for Electron
- [ ] single-user mode for Datlas
- [ ] allow to use up to 64GB of memory

**Comment by skalkin** [comment]
This is a major initiative; initial estimate for the first version is December 2022.
